### ISSUE TITLE
Research listings don’t properly wrap in mobile

### ISSUE THREAD

**Issue by florianschmidt1994** [Sparkier/sparkier.github.io#1]
![image](https://user-images.githubusercontent.com/6798306/96031332-802b4980-0e5d-11eb-8a72-a2b1f15cf383.png)

**Comment by Sparkier** [comment]
Fixed in [ab9f2c1](https://github.com/Sparkier/sparkier.github.io/commit/ab9f2c186566785d5dd752f47abeb3b64e2124ba)/[990d285](https://github.com/Sparkier/sparkier.github.io/commit/990d28537174ab5be3fe54d20737fa5028dc51b9).
